installpath=/usr/local/share/eclectus/bw.png

install:
	install -d $(installpath)/bw.png
	install -m 644 bw.png/* $(installpath)/bw.png
	install -d $(installpath)/jbw.png
	install -m 644 jbw.png/* $(installpath)/jbw.png
	install -d $(installpath)/tbw.png
	install -m 644 tbw.png/* $(installpath)/tbw.png
