installpath=/usr/local/share/eclectus/bw.png

install:
	install -d $(installpath)/bw.png
	install bw.png/* $(installpath)/bw.png
	install -d $(installpath)/jbw.png
	install jbw.png/* $(installpath)/jbw.png
	install -d $(installpath)/tbw.png
	install tbw.png/* $(installpath)/tbw.png
