#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui/ComponentPage.ui on Fri May 22 22:42:16 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(229, 324)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.componentEdit = KLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.componentEdit.setFont(font)
        self.componentEdit.setUrlDropsEnabled(False)
        self.componentEdit.setProperty("showClearButton", QtCore.QVariant(True))
        self.componentEdit.setObjectName("componentEdit")
        self.horizontalLayout_3.addWidget(self.componentEdit)
        self.includeSimilarButton = QtGui.QToolButton(Form)
        self.includeSimilarButton.setCheckable(True)
        self.includeSimilarButton.setChecked(True)
        self.includeSimilarButton.setAutoRaise(True)
        self.includeSimilarButton.setObjectName("includeSimilarButton")
        self.horizontalLayout_3.addWidget(self.includeSimilarButton)
        self.includeVariantsButton = QtGui.QToolButton(Form)
        self.includeVariantsButton.setCheckable(True)
        self.includeVariantsButton.setChecked(True)
        self.includeVariantsButton.setAutoRaise(True)
        self.includeVariantsButton.setObjectName("includeVariantsButton")
        self.horizontalLayout_3.addWidget(self.includeVariantsButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.componentSplitter = QtGui.QSplitter(Form)
        self.componentSplitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.componentSplitter.setFrameShadow(QtGui.QFrame.Plain)
        self.componentSplitter.setOrientation(QtCore.Qt.Vertical)
        self.componentSplitter.setChildrenCollapsible(False)
        self.componentSplitter.setObjectName("componentSplitter")
        self.componentView = QtWebKit.QWebView(self.componentSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.componentView.sizePolicy().hasHeightForWidth())
        self.componentView.setSizePolicy(sizePolicy)
        self.componentView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.componentView.setUrl(QtCore.QUrl("about:blank"))
        self.componentView.setObjectName("componentView")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.componentSplitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.componentResultLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.componentResultLabel.setObjectName("componentResultLabel")
        self.verticalLayout_6.addWidget(self.componentResultLabel)
        self.componentResultView = QtWebKit.QWebView(self.verticalLayoutWidget_2)
        self.componentResultView.setMinimumSize(QtCore.QSize(0, 45))
        self.componentResultView.setMaximumSize(QtCore.QSize(16777215, 80))
        self.componentResultView.setBaseSize(QtCore.QSize(0, 0))
        self.componentResultView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.componentResultView.setUrl(QtCore.QUrl("about:blank"))
        self.componentResultView.setObjectName("componentResultView")
        self.verticalLayout_6.addWidget(self.componentResultView)
        self.verticalLayout.addWidget(self.componentSplitter)
        self.label.setBuddy(self.componentEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.label.setText(kdecore.i18n("&Search:"))
        self.includeSimilarButton.setToolTip(kdecore.i18n("Include similar forms in search"))
        self.includeSimilarButton.setWhatsThis(kdecore.i18n("Include characters with similar forms in search."))
        self.includeVariantsButton.setToolTip(kdecore.i18n("Include radical variant forms in search"))
        self.includeVariantsButton.setWhatsThis(kdecore.i18n("Include variant forms for a given radical in search to easily look for variants by giving the main radical form."))
        self.componentResultLabel.setText(kdecore.i18n("Results:"))

from PyQt4 import QtWebKit
from PyKDE4.kdeui import KLineEdit
