#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from ui/HandwritingPage.ui on Tue Jun  2 12:30:04 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(270, 469)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clearButton = QtGui.QToolButton(Form)
        self.clearButton.setCheckable(False)
        self.clearButton.setChecked(False)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_3.addWidget(self.clearButton)
        self.backButton = QtGui.QToolButton(Form)
        self.backButton.setCheckable(False)
        self.backButton.setChecked(False)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_3.addWidget(self.backButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.handwritingSplitter = QtGui.QSplitter(Form)
        self.handwritingSplitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.handwritingSplitter.setFrameShadow(QtGui.QFrame.Plain)
        self.handwritingSplitter.setOrientation(QtCore.Qt.Vertical)
        self.handwritingSplitter.setChildrenCollapsible(False)
        self.handwritingSplitter.setObjectName("handwritingSplitter")
        self.handwritingView = HandwritingWidget(self.handwritingSplitter)
        self.handwritingView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.handwritingView.setObjectName("handwritingView")
        self.handwritingResultView = QtWebKit.QWebView(self.handwritingSplitter)
        self.handwritingResultView.setMinimumSize(QtCore.QSize(0, 45))
        self.handwritingResultView.setMaximumSize(QtCore.QSize(16777215, 80))
        self.handwritingResultView.setBaseSize(QtCore.QSize(0, 0))
        self.handwritingResultView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.handwritingResultView.setUrl(QtCore.QUrl("about:blank"))
        self.handwritingResultView.setObjectName("handwritingResultView")
        self.verticalLayout.addWidget(self.handwritingSplitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.clearButton.setToolTip(kdecore.i18n("Clear the drawing area"))
        self.clearButton.setWhatsThis(kdecore.i18n("Clear the drawing area"))
        self.backButton.setToolTip(kdecore.i18n("Remove the last stroke"))
        self.backButton.setWhatsThis(kdecore.i18n("Remove the last stroke"))
        self.handwritingView.setToolTip(kdecore.i18n("Draw the character using one line per stroke observing stroke order and relative placement."))
        self.handwritingView.setWhatsThis(kdecore.i18n("Draw the character using one line per stroke observing stroke order and relative placement."))

from PyQt4 import QtWebKit
from tomoeqt.handwritingwidget import HandwritingWidget
