installpath=/usr/local/share/eclectus/order.gif

install:
	install -d $(installpath)/order.gif
	install order.gif/* $(installpath)/order.gif
	install -d $(installpath)/jorder.gif
	install jorder.gif/* $(installpath)/jorder.gif
	install -d $(installpath)/torder.gif
	install torder.gif/* $(installpath)/torder.gif
