installpath=/usr/local/share/eclectus/order.gif

install:
	install -d $(installpath)/order.gif
	install -m 644 order.gif/* $(installpath)/order.gif
	install -d $(installpath)/jorder.gif
	install -m 644 jorder.gif/* $(installpath)/jorder.gif
	install -d $(installpath)/torder.gif
	install -m 644 torder.gif/* $(installpath)/torder.gif
