installpath=/usr/local/share/eclectus/bw.png.segment

install:
	install -d $(installpath)/bw.png.segment
	install -m 644 bw.png.segment/* $(installpath)/bw.png.segment
	install -d $(installpath)/jbw.png.segment
	install -m 644 jbw.png.segment/* $(installpath)/jbw.png.segment
	install -d $(installpath)/tbw.png.segment
	install -m 644 tbw.png.segment/* $(installpath)/tbw.png.segment
