installpath=/usr/local/share/eclectus/bw.png.segment

install:
	install -d $(installpath)/bw.png.segment
	install bw.png.segment/* $(installpath)/bw.png.segment
	install -d $(installpath)/jbw.png.segment
	install jbw.png.segment/* $(installpath)/jbw.png.segment
	install -d $(installpath)/tbw.png.segment
	install tbw.png.segment/* $(installpath)/tbw.png.segment
