installpath=/usr/local/share/eclectus/red.png

install:
	install -d $(installpath)/red.png
	install -m 644 red.png/* $(installpath)/red.png
	install -d $(installpath)/jred.png
	install -m 644 jred.png/* $(installpath)/jred.png
	#install -d $(installpath)/tred.png
	#install -m 644 tred.png/* $(installpath)/tred.png
