installpath=/usr/local/share/eclectus/red.png

install:
	install -d $(installpath)/red.png
	install red.png/* $(installpath)/red.png
	install -d $(installpath)/jred.png
	install jred.png/* $(installpath)/jred.png
	#install -d $(installpath)/tred.png
	#install tred.png/* $(installpath)/tred.png
